// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9AZCeLV-BAwcZlSUcpCS_762jhVM0Y6A',
    appId: '1:733603630832:web:7c4af754b970216f987c35',
    messagingSenderId: '733603630832',
    projectId: 'harvestdata-50209',
    authDomain: 'harvestdata-50209.firebaseapp.com',
    databaseURL: 'https://harvestdata-50209-default-rtdb.firebaseio.com',
    storageBucket: 'harvestdata-50209.appspot.com',
    measurementId: 'G-6P5FKH0DHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx2bPITkzqXaVgj1hfAlI_O8no_qxRTm8',
    appId: '1:733603630832:android:6830c66de9620f5b987c35',
    messagingSenderId: '733603630832',
    projectId: 'harvestdata-50209',
    databaseURL: 'https://harvestdata-50209-default-rtdb.firebaseio.com',
    storageBucket: 'harvestdata-50209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX5S2dKoBL7FZxiT4qFNU70i4Vs1vbc8Y',
    appId: '1:733603630832:ios:d43ce2dd729598f2987c35',
    messagingSenderId: '733603630832',
    projectId: 'harvestdata-50209',
    storageBucket: 'harvestdata-50209.appspot.com',
    iosBundleId: 'com.example.harvestDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX5S2dKoBL7FZxiT4qFNU70i4Vs1vbc8Y',
    appId: '1:733603630832:ios:d43ce2dd729598f2987c35',
    messagingSenderId: '733603630832',
    projectId: 'harvestdata-50209',
    storageBucket: 'harvestdata-50209.appspot.com',
    iosBundleId: 'com.example.harvestDart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9AZCeLV-BAwcZlSUcpCS_762jhVM0Y6A',
    appId: '1:733603630832:web:fc39c6f0f41e082c987c35',
    messagingSenderId: '733603630832',
    projectId: 'harvestdata-50209',
    authDomain: 'harvestdata-50209.firebaseapp.com',
    storageBucket: 'harvestdata-50209.appspot.com',
    measurementId: 'G-GFKDYCF92S',
  );
}