name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    # Define the job to run on the latest Ubuntu environment
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'


      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Flutter Release Action
        uses: Oberhauser-Dev/flutter-release-action@v0
        with:
          token: ${{ github.token }}
          dry-run: true
          app-name: 'Harvest Guard'
          app-version: ${{ github.ref_name }}
          tag: ${{ github.ref }}
          build-type: 'apk'